name: kidtastic_flutter
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.2.1
  cupertino_icons: ^1.0.8
  intl: any
  drift: ^2.28.1
  path: ^1.9.1
  path_provider: ^2.1.5
  responsive_framework: ^1.5.1
  window_manager: ^0.5.1
  smooth_page_indicator: ^1.2.0
  record: ^6.1.2
  sherpa_onnx: ^1.12.15
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  confetti: ^0.8.0
  audioplayers: ^6.5.1
  # flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.0
  drift_dev: ^2.28.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/Vag/
    - assets/fruits/
    - assets/animals/
    - assets/shapes/
    - assets/models/sherpa-onnx-streaming-zipformer-en-kroko/
    - assets/avatars/
    - assets/pronunciation/
    - assets/audios/
    - assets/shapes/
    - assets/backgrounds/

  fonts:
    - family: Vag
      fonts:
        - asset: assets/fonts/Vag/Vag_Light.ttf
          weight: 400
        - asset: assets/fonts/Vag/Vag_Bold.ttf
          weight: 600
        - asset: assets/fonts/Vag/Vag_Black.ttf
          weight: 700
